name: List services in GCP
on:
  workflow_dispatch

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/211464305662/locations/global/workloadIdentityPools/github-pools/providers/github-providers'
          service_account: 'github-actions-sa@white-resolver-460502-v9.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: gcloud projects list
